server:
    port: 5555

spring:
    main:
        web-application-type: reactive
    cloud:
        gateway:
            globalcors:
                add-to-simple-url-handler-mapping: true
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"
            discovery:
                locator:
                    enabled: true
            routes:
                - id: userservice
                  uri: lb://USERSERVICE
                  predicates:
                    - Path=/user/**

