server:
    port: 5555

spring:
    main:
        web-application-type: reactive
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: pieceservice
                  uri: lb://PIECESERVICE
                  predicates:
                    - Path=/pieces/**